### ISSUE TITLE
Adding Account Fails

### ISSUE THREAD

**Issue by liamdemafelix** [blesta/module-vultr#1]
I tried to add an account, it fails. Debug shows:

```
Warning: Uncaught UnknownException: require_once(/mypath/components/modules/vultr/apis/commands/vultr_account.php): failed to open stream: No such file or directory in /mypath/components/modules/vultr/apis/vultr_api.php:112 Stack trace: #0 [internal function]: UnknownException::setErrorHandler(2, 'require_once(/h...', '/home/remotese/...', 112, Array) #1 /mypath/vendors/monolog/monolog/src/Monolog/ErrorHandler.php(164): call_user_func(Array, 2, 'require_once(/h...', '/home/remotese/...', 112, Array) #2 /mypath/components/modules/vultr/apis/vultr_api.php(112): Monolog\ErrorHandler->handleError(2, 'require_once(/h...', '/home/remotese/...', 112, Array) #3 /mypath/components/modules/vultr/apis/vultr_api.php(112): require_once() #4 /mypath/components/modules/vultr/vultr.php(2607): VultrApi->loadCommand('vultr_account') #5 [inte in /mypath/components/modules/vultr/apis/vultr_api.php on line 112

Fatal error: VultrApi::loadCommand(): Failed opening required '/mypath/components/modules/vultr/apis/commands/vultr_account.php' (include_path='.:/opt/alt/php71/usr/share/pear') in /mypath/components/modules/vultr/apis/vultr_api.php on line 112
```

**Comment by tysonphillips** [comment]
You receive that error after downloading and using these files from github?
https://github.com/blesta/module-vultr/archive/master.zip

**Comment by liamdemafelix** [comment]
Tried the master branch and the 1.1.1 release, had the same results.

For what it's worth, I'm on PHP 7.1.

**Comment by mrhasbean** [comment]
I'm getting this too. There is no "commands" folder in apis. Seems an entire folder is missing from the distro?

From vultr_api.php:

public function loadCommand($command)
{
    require_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'commands' . DIRECTORY_SEPARATOR . $command . '.php';
}

Hence the error?
"failed to open stream: **No such file or directory**"

Evaluating Blesta at present. I really like what I see in the product, but ten days with no apparent fix to this doesn't exactly inspire a lot of confidence. :(

**Comment by mrhasbean** [comment]
Just did some hunting, and the forum thread [HERE](https://www.blesta.com/forums/index.php?/topic/11081-vultr-module-alpha/) has a zip of a prerelease that contains a commands folder inside the apis folder. Seems to have gone MIA in the release version. A fix would be nice.

**Comment by tysonphillips** [comment]
Please use v1.1.2 of the module, which addresses the Vultr API commands
