### ISSUE TITLE
This module need an update

### ISSUE THREAD

**Issue by shoquebd** [blesta/module-vultr#34]
Hello

Vultr now using **API v2** which using alphanumeric value for server ID. Please update this module to make it compatible with API v2. API docs can be found here https://www.vultr.com/api/.

Thanks

**Comment by breicobrei** [comment]
> Hello
> 
> Vultr now using **API v2** which using alphanumeric value for server ID. Please update this module to make it compatible with API v2. API docs can be found here https://www.vultr.com/api/.
> 
> Thanks

Hello, I join the blesta purchase if this plugin is up to date. Thank you.

**Comment by CodeMeZone** [comment]
Anything on this? 

v1 is going to go offline soon.

**Comment by JReissmueller** [comment]
This should be resolved as of #39
